version: "3.9"
services:

  node-application:
    build: .
    image: express-office-lunch
    container_name: express-office-lunch
    ports:
      - "3012:3001"
    restart: always
    env_file:
      - .env
    networks:
      - internal_mysql_network

networks:
  internal_mysql_network:
    external: true
